### ISSUE TITLE
Undefined and Missing Functions

### ISSUE THREAD

**Issue by CeruleanSky** [sdrforengineers/code#1]
The function ```SetPlotSize``` and ```SetPlotFont``` used in the code is undefined, they are used in the following list of files:

```
chapter.m 
chapter2.m
chapter3.m
chapter4.m
chapter5.m
chapter6.m
psk.m
robin.m
sfdr_test.m
simulated_DAC.m
time-alias.m
updownsample.m
```

I am using MatLab R2018a, I'll update this issue with any undefined or missing functions found in the examples as I come across them.

**Comment by tfcollins** [comment]
Those function calls were specific to making things look nice in Latex.  They've been removed in those listed scripts.

If anything else isn't functioning please let me know.  Thanks for the report.
