### ISSUE TITLE
Does this function 'getOFDMPreambleAndPilot' comes from any toolbox?

### ISSUE THREAD

**Issue by ashsheik** [sdrforengineers/code#2]
Hi, 
I was looking for some implementation of Schmidl-cox and I bumped onto this book and pluto-SDR and its really amazing. 
I was trying to run the code and guess have a dependency on **getOFDMPreambleAndPilot** function.  What toolbox do I need in order to successfully run all the codes on this git? Or Do I need to implement this on my own ?

Ashish

**Comment by tfcollins** [comment]
That function is in the Communications Toolbox, its part of this demo:  https://www.mathworks.com/help/comm/examples/ofdm-synchronization.html?searchHighlight=getOFDMPreambleAndPilot&s_tid=doc_srchtitle

**Comment by ashsheik** [comment]
Thanks . I will install comm toolbox and then use the scripts.
